spring.application.name=webproject2

spring.datasource.url=jdbc:mysql://localhost:3306/webproject2?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Chrismysql13.papei075

# ???????? ??? SQL queries ??? terminal (??????? ???? ??? debugging)
spring.jpa.show-sql=true

# ???????? ????????? ??? ???????
spring.jpa.hibernate.ddl-auto=update