spring.application.name=webproject2
# ??????? ?? MySQL (?????? ?? 'onoma_vasis' ?? ?? ????? ??? ????? ??? ???????? ??? Workbench)
spring.datasource.url=jdbc:mysql://localhost:3306/webproject2?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=??_password_???_????_mysql

# ???????? ??? SQL queries ??? terminal (??????? ???? ??? debugging)
spring.jpa.show-sql=true

# ???????? ????????? ??? ???????
spring.jpa.hibernate.ddl-auto=update